greeting:
  welcome: ${spring.application.name}
#  welcome: You are using ${spring.application.name}.
taco:
  orders:
    page-size: 12
  discount:
    codes:
      abcdef: 10
      defr: 20

logging:
  level:
    tacos: DEBUG

spring:
  data:
    rest:
      base-path: /api
